zero: Merge NFC Hal From A8 2016 Oreo (A810SKSU2CRG3)
TheMuppets/proprietary_vendor_samsung pull request #1094
Opened 2018-09-22 09:58 UTC by enesuzun2002

2018-09-28 08:26 UTC, npjohnson requested changes
Does the current maintainer (CC: @Usaamah99) agree with this change?

2018-09-28 08:26 UTC, npjohnson commented on zero-common/zero-common-vendor.mk
> +    vendor/samsung/zero-common/proprietary/vendor/lib64/hw/nfc_nci.default.so:system/vendor/lib64/hw/nfc_nci.default.so \
This isn't script generated, which we require. If it was, the alphabetization would've happened.

2018-10-01 14:26 UTC, enesuzun2002 commented on zero-common/zero-common-vendor.mk
> +    vendor/samsung/zero-common/proprietary/vendor/lib64/hw/nfc_nci.default.so:system/vendor/lib64/hw/nfc_nci.default.so \
yes it is not, i have added them myself to list. Also yes @Usaamah99 know about this

2018-10-01 14:32 UTC, enesuzun2002 commented
i will create new one right now this one has some issues

2018-10-01 14:54 UTC, enesuzun2002 commented
it is fine and can be merged

2018-10-01 21:17 UTC, npjohnson commented
@enesuzun2002 @Usaamah99 said this is NOT to be merged right now. When he approves it, we can merge.

2018-10-01 21:18 UTC, npjohnson commented
Also, the comments aren't fixed. This wasn't script gen'd.

2018-10-14 05:56 UTC, closed without merging